spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/accounts_db

server:
  port: 8080

logging:
  level:
    root: INFO
    ntt.ntt_ms_accounts: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: always
